REMOVE= sudo rm -Rf

all:
	gcc main.c -o main 

install:
	@echo "This is gonna be your install target"
	./main
clean:
	@echo "This is gonna be your clean target"

uninstall:
	@echo "This is gonna be your uninstall target"
	$(REMOVE) main